### ISSUE TITLE
Sliding Window Function - incomplete information

### ISSUE THREAD

**Issue by santos-ab-1** [MicrosoftDocs/azure-reference-other#151]
There is no description on why there is a window that continues to capture events even when there were no occurrences of a new event/tweet. 

There was also mention of "entry" and "exit" of events, but no additional information on its implications on the window function and where to get more information about it. For example, an "exit" of an event supposedly triggers the sliding window, but when does an event "exit"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aea19668-9e4e-ee61-e5ec-725746f0c6fc
* Version Independent ID: bac2197e-1698-6bc1-0282-d62154504bcc
* Content: [Sliding Window (Azure Stream Analytics) - Stream Analytics Query](https://docs.microsoft.com/en-us/stream-analytics-query/sliding-window-azure-stream-analytics)
* Content Source: [stream-analytics-docs/sliding-window-azure-stream-analytics.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/stream-analytics-docs/sliding-window-azure-stream-analytics.md)
* Service: **stream-analytics**
* GitHub Login: @JSeb225
* Microsoft Alias: **jeanb**

**Comment by JasonWHowell** [comment]
@JSeb225 @Fleid this docs feedback came in recently. Please triage at your conveinance.

**Comment by Fleid** [comment]
Hi @santos-ab-1,
Is your comment about the chart, where we see 2 windows with event number 8? 
Because that last window should not exist. Its creation is triggered by the exit of event 8 but it's empty so it won't be output.

Another way to look at entry/exit of events is to think about what triggers the creation of an output event.
The event 1 at t10 in the example will trigger the creation of 2 output events:
- one at t10 that will aggregate all events from t0 to t10 : its "entry" in the sliding window
- another one at t21, that aggregates events from t11 to 21 : its "exit" of the sliding window

I hope that helps. 
I will fix the illustration and hopefully make it clearer also.

**Comment by Fleid** [comment]
#please-close
